spring: 
 datasource: 
  url: jdbc:mysql://localhost:3306/shopping_cart
  username: root
  password: 1234
  
 jpa:
  hibernate:
   ddl: none
   use-new-id-generator-mappings: true
   show-sql: true